<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
const DB_FILE = __DIR__ . '/monitoring.sqlite';
const SECRET_FILE = __DIR__ . '/app.key';
const SCORE_VALUES = ['Compliant'=>3,'Partially Compliant'=>2,'Not Compliant'=>1];
function out(array $data,int $status=200):never{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function body():array{$v=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($v)?$v:[];}
function now():string{return gmdate('c');}
function clean_user(mixed $v):string{return preg_replace('/[^a-z0-9._-]/','',strtolower(trim((string)$v)))??'';}
function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',[...str_split(bin2hex($b),4)]);}
function db():PDO{static $db;if($db)return $db;if(!file_exists(DB_FILE)||!file_exists(SECRET_FILE))out(['error'=>'Database setup is required. Open /api/setup.php first.'],503);try{$db=new PDO('sqlite:'.DB_FILE,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_TIMEOUT=>15]);$db->exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=15000; PRAGMA synchronous=NORMAL; PRAGMA temp_store=MEMORY; PRAGMA cache_size=-20000; PRAGMA wal_autocheckpoint=1000;');return $db;}catch(Throwable){out(['error'=>'The database is unavailable. Contact the site administrator.'],503);}}
function write_retry(callable $operation,int $attempts=8):mixed{$last=null;for($i=0;$i<$attempts;$i++){try{return $operation();}catch(PDOException $e){$last=$e;$message=strtolower($e->getMessage());if(!str_contains($message,'locked')&&!str_contains($message,'busy'))throw $e;if($i+1<$attempts)usleep(min(1000000,50000*(2**$i))+random_int(0,50000));}}throw $last;}
function secret():string{return trim((string)file_get_contents(SECRET_FILE));}
function b64(string $v):string{return rtrim(strtr(base64_encode($v),'+/','-_'),'=');}
function b64d(string $v):string{return (string)base64_decode(strtr($v,'-_','+/'));}
function sign_token(array $p):string{$b=b64((string)json_encode($p));return $b.'.'.b64(hash_hmac('sha256',$b,secret(),true));}
function verify_token(string $t):?array{$p=explode('.',$t);if(count($p)!==2||!hash_equals(b64(hash_hmac('sha256',$p[0],secret(),true)),$p[1]))return null;$d=json_decode(b64d($p[0]),true);return is_array($d)&&($d['exp']??0)>time()?$d:null;}
function score(array $items):array{$earned=0;$count=0;foreach($items as $x){$s=$x['status']??'';if(isset(SCORE_VALUES[$s])){$earned+=SCORE_VALUES[$s];$count++;}}$max=$count*3;$pct=$max?round($earned/$max*100,2):null;$rating=$pct===null?'Not yet rated':($pct>=90?'Outstanding':($pct>=80?'Very Satisfactory':($pct>=70?'Satisfactory':($pct>=60?'Needs Improvement':'Needs Immediate Technical Assistance'))));return ['earnedPoints'=>$earned,'maximumPoints'=>$max,'applicableItems'=>$count,'percentage'=>$pct,'rating'=>$rating];}
function user_row(array $r):array{return ['id'=>$r['id'],'username'=>$r['username'],'name'=>$r['name'],'role'=>$r['role'],'status'=>$r['status'],'district'=>$r['district'],'schoolName'=>$r['school_name'],'schoolId'=>$r['school_id'],'createdAt'=>$r['created_at']];}
function current_user(bool $admin=false):array{$h=$_SERVER['HTTP_AUTHORIZATION']??'';$p=verify_token(str_starts_with($h,'Bearer ')?substr($h,7):'');if(!$p)out(['error'=>'Your session has expired. Please log in again.'],401);$s=db()->prepare('SELECT * FROM users WHERE id=? AND status="active"');$s->execute([$p['id']??'']);$u=$s->fetch();if(!$u)out(['error'=>'Your session has expired. Please log in again.'],401);if($admin&&$u['role']!=='admin')out(['error'=>'Administrator access required.'],403);return $u;}
function report_row(array $r,bool $withData=true):array{$x=['id'=>$r['id'],'userId'=>$r['user_id'],'username'=>$r['username'],'district'=>$r['district'],'schoolName'=>$r['school_name'],'schoolId'=>$r['school_id'],'submittedAt'=>$r['submitted_at'],'status'=>$r['status'],'score'=>json_decode($r['score'],true)];if($withData)$x['data']=json_decode($r['data'],true);return $x;}
$route=trim((string)($_GET['route']??''),'/');$method=$_SERVER['REQUEST_METHOD'];$db=db();
try{
if($route==='register'&&$method==='POST'){$b=body();$un=clean_user($b['username']??'');if(empty($b['district'])||empty($b['schoolName'])||empty($b['schoolId'])||!$un||empty($b['password']))out(['error'=>'All registration fields are required.'],400);if(($b['password']??'')!==($b['confirmPassword']??''))out(['error'=>'Passwords do not match.'],400);if(strlen((string)$b['password'])<8)out(['error'=>'Password must be at least 8 characters.'],400);$s=$db->prepare('SELECT 1 FROM users WHERE username=?');$s->execute([$un]);if($s->fetchColumn())out(['error'=>'Username is already in use.'],409);$values=[uuid(),$un,password_hash((string)$b['password'],PASSWORD_DEFAULT),trim((string)$b['schoolName']),'user','inactive',trim((string)$b['district']),trim((string)$b['schoolName']),trim((string)$b['schoolId']),now()];try{write_retry(function()use($db,$values){$s=$db->prepare('INSERT INTO users(id,username,password_hash,name,role,status,district,school_name,school_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)');return $s->execute($values);});}catch(PDOException $e){if(str_contains(strtolower($e->getMessage()),'unique'))out(['error'=>'Username is already in use.'],409);throw $e;}out(['ok'=>true]);}
if($route==='login'&&$method==='POST'){$b=body();$s=$db->prepare('SELECT * FROM users WHERE username=?');$s->execute([clean_user($b['username']??'')]);$u=$s->fetch();if(!$u||$u['status']!=='active'||!password_verify((string)($b['password']??''),$u['password_hash']))out(['error'=>'Invalid username or password.'],401);out(['token'=>sign_token(['id'=>$u['id'],'role'=>$u['role'],'exp'=>time()+28800]),'user'=>user_row($u)]);}
if($route==='me'&&$method==='GET')out(['user'=>user_row(current_user())]);
if($route==='users'&&$method==='GET'){current_user(true);out(['users'=>array_map('user_row',$db->query('SELECT * FROM users ORDER BY created_at DESC')->fetchAll())]);}
if($route==='users/update'&&$method==='POST'){current_user(true);$b=body();if(!in_array($b['status']??'',['active','inactive'],true))out(['error'=>'Invalid account status.'],400);write_retry(function()use($db,$b){$s=$db->prepare('UPDATE users SET status=? WHERE id=? AND role<>"admin"');return $s->execute([$b['status'],$b['id']??'']);});out(['ok'=>true]);}
if($route==='users/delete'&&$method==='POST'){current_user(true);$b=body();write_retry(function()use($db,$b){$s=$db->prepare('DELETE FROM users WHERE id=? AND role<>"admin"');return $s->execute([$b['id']??'']);});out(['ok'=>true]);}
if($route==='draft'&&$method==='GET'){$u=current_user();$s=$db->prepare('SELECT data FROM drafts WHERE user_id=?');$s->execute([$u['id']]);$v=$s->fetchColumn();out(['draft'=>$v?json_decode((string)$v,true):null]);}
if($route==='draft'&&$method==='POST'){$u=current_user();$b=body();$data=is_array($b['data']??null)?$b['data']:[];$data['score']=score($data['checklist']??[]);$data['savedAt']=now();$values=[$u['id'],json_encode($data,JSON_UNESCAPED_UNICODE),$data['savedAt']];write_retry(function()use($db,$values){$s=$db->prepare('INSERT INTO drafts(user_id,data,saved_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data,saved_at=excluded.saved_at');return $s->execute($values);});out(['ok'=>true,'score'=>$data['score'],'savedAt'=>$data['savedAt']]);}
if($route==='submit'&&$method==='POST'){$u=current_user();if($u['role']==='admin')out(['error'=>'Administrator cannot submit a school report.'],400);$b=body();$data=is_array($b['data']??null)?$b['data']:[];$data['score']=score($data['checklist']??[]);$id=uuid();$submitted=now();$values=[$id,$u['id'],$u['username'],$u['district'],$u['school_name'],$u['school_id'],$submitted,'Submitted',json_encode($data['score']),json_encode($data,JSON_UNESCAPED_UNICODE)];write_retry(function()use($db,$values){$s=$db->prepare('INSERT INTO reports(id,user_id,username,district,school_name,school_id,submitted_at,status,score,data) VALUES(?,?,?,?,?,?,?,?,?,?)');return $s->execute($values);});out(['ok'=>true,'id'=>$id,'score'=>$data['score']]);}
if($route==='submissions'&&$method==='GET'){current_user(true);$rows=$db->query('SELECT * FROM reports ORDER BY submitted_at DESC LIMIT 5000')->fetchAll();out(['submissions'=>array_map(fn($r)=>report_row($r,true),$rows)]);}
if($route==='submission'&&$method==='GET'){current_user(true);$s=$db->prepare('SELECT * FROM reports WHERE id=?');$s->execute([$_GET['id']??'']);$r=$s->fetch();if(!$r)out(['error'=>'Report not found.'],404);out(['report'=>report_row($r,true)]);}
if($route==='my-submissions'&&$method==='GET'){$u=current_user();$s=$db->prepare('SELECT * FROM reports WHERE user_id=? ORDER BY submitted_at DESC');$s->execute([$u['id']]);out(['submissions'=>array_map(fn($r)=>report_row($r,false),$s->fetchAll())]);}
if($route==='dashboard'&&$method==='GET'){current_user(true);$registered=(int)$db->query('SELECT COUNT(*) FROM users WHERE role="user"')->fetchColumn();$active=(int)$db->query('SELECT COUNT(*) FROM users WHERE role="user" AND status="active"')->fetchColumn();$districts=(int)$db->query('SELECT COUNT(DISTINCT district) FROM users WHERE role="user" AND district<>""')->fetchColumn();$total=(int)$db->query('SELECT COUNT(*) FROM reports')->fetchColumn();$recent=array_map(fn($r)=>report_row($r,true),$db->query('SELECT * FROM reports ORDER BY submitted_at DESC LIMIT 8')->fetchAll());$by=$db->query('SELECT district,COUNT(*) count FROM reports GROUP BY district ORDER BY count DESC')->fetchAll();out(['registeredSchools'=>$registered,'submissions'=>$total,'activeUsers'=>$active,'districts'=>$districts,'recent'=>$recent,'byDistrict'=>array_map(fn($x)=>['district'=>$x['district'],'count'=>(int)$x['count']],$by)]);}
if($route==='change-password'&&$method==='POST'){$u=current_user(true);$b=body();if(!password_verify((string)($b['currentPassword']??''),$u['password_hash']))out(['error'=>'Current password is incorrect.'],400);if(strlen((string)($b['newPassword']??''))<10)out(['error'=>'New password must be at least 10 characters.'],400);$hash=password_hash((string)$b['newPassword'],PASSWORD_DEFAULT);write_retry(function()use($db,$hash,$u){$s=$db->prepare('UPDATE users SET password_hash=? WHERE id=?');return $s->execute([$hash,$u['id']]);});out(['ok'=>true]);}
out(['error'=>'Not found.'],404);
}catch(PDOException $e){error_log($e->getMessage());out(['error'=>'Database operation failed. Please try again.'],500);}catch(Throwable $e){error_log($e->getMessage());out(['error'=>'Server error.'],500);}
