<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
const DB_FILE = __DIR__ . '/monitoring.sqlite';
const SECRET_FILE = __DIR__ . '/app.key';
const SCORE_VALUES = ['Compliant'=>3,'Partially Compliant'=>2,'Not Compliant'=>1];
function out(array $data,int $status=200):never{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function body():array{$v=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($v)?$v:[];}
function now():string{return gmdate('c');}
function clean_user(mixed $v):string{return preg_replace('/[^a-z0-9._-]/','',strtolower(trim((string)$v)))??'';}
function district_names():array{return ['Alcantara','Alcoy','Alegria','Aloguinsan','Argao I','Argao II','Asturias I','Asturias II','Badian','Balamban I','Balamban II','Bantayan I','Bantayan II','Barili I','Barili II','Boljoon','Borbon','Carmen','Catmon','Compostela','Consolacion I','Consolacion II','Cordova','Daan Bantayan I','Daan Bantayan II','Dalaguete I','Dalaguete II','Dumanjug I','Dumanjug II','Ginatilan','Liloan','Madridejos','Malabuyoc','Medellin','Minglanilla I','Minglanilla II','Moalboal','Oslob','Pilar','Pinamungajan I','Pinamungajan II','Poro','Ronda','Samboan','San Fernando I','San Fernando II','San Francisco','San Remigio I','San Remigio II','Santa Fe','Santander','Sibonga','Sogod','Tabogon','Tabuelan','Tuburan I','Tuburan II','Tudela'];}
function district_key(mixed $value):string{$v=strtolower(trim((string)$value));$v=str_replace(['Ⅰ','ⅰ','Ⅱ','ⅱ'],['1','1','2','2'],$v);$v=preg_replace('/\b(?:district|distict|distrct)\b/',' ',$v)??$v;$v=preg_replace('/\bii\b/','2',$v)??$v;$v=preg_replace('/\bi\b/','1',$v)??$v;return preg_replace('/[^a-z0-9]/','',$v)??'';}
function canonical_district(mixed $value):?string{static $map=null;if($map===null){$map=[];foreach(district_names() as $name)$map[district_key($name)]=$name;}$key=district_key($value);if(!$key)return null;$aliases=['bantayanl'=>'Bantayan I'];if(isset($aliases[$key]))return $aliases[$key];if(isset($map[$key]))return $map[$key];$limit=strlen($key)<=6?1:2;$best=null;$bestDistance=PHP_INT_MAX;$tied=false;foreach($map as $officialKey=>$name){$distance=levenshtein($key,$officialKey);if($distance<$bestDistance){$best=$name;$bestDistance=$distance;$tied=false;}elseif($distance===$bestDistance)$tied=true;}return !$tied&&$bestDistance<=$limit?$best:null;}
function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',[...str_split(bin2hex($b),4)]);}
function ensure_schema(PDO $db):void{$columns=array_column($db->query('PRAGMA table_info(users)')->fetchAll(),'name');if(!in_array('email',$columns,true)){try{$db->exec('ALTER TABLE users ADD COLUMN email TEXT NOT NULL DEFAULT ""');}catch(PDOException $e){if(!str_contains(strtolower($e->getMessage()),'duplicate column'))throw $e;}}if(!in_array('profile_photo',$columns,true)){try{$db->exec('ALTER TABLE users ADD COLUMN profile_photo TEXT NOT NULL DEFAULT ""');}catch(PDOException $e){if(!str_contains(strtolower($e->getMessage()),'duplicate column'))throw $e;}}$indexes=array_column($db->query('PRAGMA index_list(users)')->fetchAll(),'name');if(!in_array('users_email_nocase_unique_idx',$indexes,true))$db->exec('CREATE UNIQUE INDEX IF NOT EXISTS users_email_nocase_unique_idx ON users(email COLLATE NOCASE) WHERE email<>""');$db->exec('CREATE TABLE IF NOT EXISTS presence (user_id TEXT PRIMARY KEY,last_seen TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE); CREATE INDEX IF NOT EXISTS presence_last_seen_idx ON presence(last_seen);');}
function touch_presence(PDO $db,string $userId):void{write_retry(function()use($db,$userId){$s=$db->prepare('INSERT INTO presence(user_id,last_seen) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET last_seen=excluded.last_seen');return $s->execute([$userId,now()]);});}
function online_cutoff():string{return gmdate('c',time()-180);}
function db():PDO{static $db;if($db)return $db;if(!file_exists(DB_FILE)||!file_exists(SECRET_FILE))out(['error'=>'Database setup is required. Open /api/setup.php first.'],503);try{$db=new PDO('sqlite:'.DB_FILE,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_TIMEOUT=>15]);$db->exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=15000; PRAGMA synchronous=NORMAL; PRAGMA temp_store=MEMORY; PRAGMA cache_size=-20000; PRAGMA wal_autocheckpoint=1000;');ensure_schema($db);return $db;}catch(Throwable){out(['error'=>'The database is unavailable. Contact the site administrator.'],503);}}
function write_retry(callable $operation,int $attempts=8):mixed{$last=null;for($i=0;$i<$attempts;$i++){try{return $operation();}catch(PDOException $e){$last=$e;$message=strtolower($e->getMessage());if(!str_contains($message,'locked')&&!str_contains($message,'busy'))throw $e;if($i+1<$attempts)usleep(min(1000000,50000*(2**$i))+random_int(0,50000));}}throw $last;}
function normalize_user_district(PDO $db,array $user):array{if(($user['role']??'')==='admin')return $user;$canonical=canonical_district($user['district']??'');if(!$canonical||$canonical===($user['district']??''))return $user;$draft=$db->prepare('SELECT data FROM drafts WHERE user_id=?');$draft->execute([$user['id']]);$draftData=$draft->fetchColumn();$draftJson=null;if($draftData){$decoded=json_decode((string)$draftData,true);if(is_array($decoded)){$decoded['district']=$canonical;$draftJson=json_encode($decoded,JSON_UNESCAPED_UNICODE);}}write_retry(function()use($db,$user,$canonical,$draftJson){$db->beginTransaction();try{$s=$db->prepare('UPDATE users SET district=? WHERE id=?');$s->execute([$canonical,$user['id']]);$s=$db->prepare('UPDATE reports SET district=? WHERE user_id=?');$s->execute([$canonical,$user['id']]);if($draftJson!==null){$s=$db->prepare('UPDATE drafts SET data=? WHERE user_id=?');$s->execute([$draftJson,$user['id']]);}$db->commit();return true;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}});$user['district']=$canonical;return $user;}
function secret():string{return trim((string)file_get_contents(SECRET_FILE));}
function b64(string $v):string{return rtrim(strtr(base64_encode($v),'+/','-_'),'=');}
function b64d(string $v):string{return (string)base64_decode(strtr($v,'-_','+/'));}
function sign_token(array $p):string{$b=b64((string)json_encode($p));return $b.'.'.b64(hash_hmac('sha256',$b,secret(),true));}
function verify_token(string $t):?array{$p=explode('.',$t);if(count($p)!==2||!hash_equals(b64(hash_hmac('sha256',$p[0],secret(),true)),$p[1]))return null;$d=json_decode(b64d($p[0]),true);return is_array($d)&&($d['exp']??0)>time()?$d:null;}
function score(array $items):array{$earned=0;$count=0;foreach($items as $x){$s=$x['status']??'';if(isset(SCORE_VALUES[$s])){$earned+=SCORE_VALUES[$s];$count++;}}$max=$count*3;$pct=$max?round($earned/$max*100,2):null;$rating=$pct===null?'Not yet rated':($pct>=90?'Outstanding':($pct>=80?'Very Satisfactory':($pct>=70?'Satisfactory':($pct>=60?'Needs Improvement':'Needs Immediate Technical Assistance'))));return ['earnedPoints'=>$earned,'maximumPoints'=>$max,'applicableItems'=>$count,'percentage'=>$pct,'rating'=>$rating];}
function user_row(array $r,bool $includePhoto=true):array{$x=['id'=>$r['id'],'username'=>$r['username'],'email'=>$r['email']??'','name'=>$r['name'],'role'=>$r['role'],'status'=>$r['status'],'district'=>$r['district'],'districtValid'=>($r['role']==='admin'||canonical_district($r['district'])!==null),'schoolName'=>$r['school_name'],'schoolId'=>$r['school_id'],'createdAt'=>$r['created_at']];if($includePhoto)$x['profilePhoto']=$r['profile_photo']??'';return $x;}
function temporary_password():string{$alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';$password='EiE!';for($i=0;$i<10;$i++)$password.=$alphabet[random_int(0,strlen($alphabet)-1)];return $password;}
function current_user(bool $admin=false):array{$h=$_SERVER['HTTP_AUTHORIZATION']??'';$p=verify_token(str_starts_with($h,'Bearer ')?substr($h,7):'');if(!$p)out(['error'=>'Your session has expired. Please log in again.'],401);$s=db()->prepare('SELECT * FROM users WHERE id=? AND status="active"');$s->execute([$p['id']??'']);$u=$s->fetch();if(!$u)out(['error'=>'Your session has expired. Please log in again.'],401);$u=normalize_user_district(db(),$u);if($admin&&$u['role']!=='admin')out(['error'=>'Administrator access required.'],403);return $u;}
function report_row(array $r,bool $withData=true):array{$submitted=strtotime((string)$r['submitted_at'])?:0;$editableUntil=$submitted+86400;$x=['id'=>$r['id'],'userId'=>$r['user_id'],'username'=>$r['username'],'district'=>$r['district'],'schoolName'=>$r['school_name'],'schoolId'=>$r['school_id'],'submittedAt'=>$r['submitted_at'],'status'=>$r['status'],'score'=>json_decode($r['score'],true),'editableUntil'=>gmdate('c',$editableUntil),'canEdit'=>time()<=$editableUntil];if($withData)$x['data']=json_decode($r['data'],true);return $x;}
function dashboard_metrics(array $rows):array{$answered=0;$expected=0;$emergencies=0;$ta=0;$taOpen=0;$taOngoing=0;$continuity=['HAYO'=>0,'HINAY'=>0,'HINGA'=>0,'HINTO'=>0];$hazards=[];$domains=[];foreach($rows as $r){$data=json_decode((string)$r['data'],true);if(!is_array($data))$data=[];$checklist=is_array($data['checklist']??null)?$data['checklist']:[];$expected+=count($checklist)?:27;foreach($checklist as $item){$status=(string)($item['status']??'');$movs=is_array($item['movChecks']??null)?$item['movChecks']:[];if($status==='Not Applicable'||count($movs)>0)$answered++;$domain=(string)($item['domain']??'Other');if(!isset($domains[$domain]))$domains[$domain]=['earned'=>0,'maximum'=>0,'applicable'=>0];if(isset(SCORE_VALUES[$status])){$domains[$domain]['earned']+=SCORE_VALUES[$status];$domains[$domain]['maximum']+=3;$domains[$domain]['applicable']++;}}$emergencyRows=is_array($data['emergencies']??null)?$data['emergencies']:[];$emergencies+=count($emergencyRows);foreach($emergencyRows as $item){$name=trim((string)($item['hazardType']??''))?:'Not specified';$hazards[$name]=($hazards[$name]??0)+1;}$continuityRows=is_array($data['continuityActivations']??null)?$data['continuityActivations']:[];if(!$continuityRows&&!empty($data['continuityLevel']))$continuityRows=[['level'=>$data['continuityLevel']]];foreach($continuityRows as $item){$level=strtoupper((string)($item['level']??''));foreach(array_keys($continuity) as $name)if(str_starts_with($level,$name)){$continuity[$name]++;break;}}$taRows=is_array($data['technicalAssistanceRecords']??null)?$data['technicalAssistanceRecords']:[];$ta+=count($taRows);foreach($taRows as $item){$status=(string)($item['taStatus']??'');if($status==='Open')$taOpen++;if($status==='Ongoing')$taOngoing++;}}$domainPerformance=[];foreach($domains as $domain=>$values)$domainPerformance[]=['domain'=>preg_replace('/^[A-H]\.\s*/','',$domain),'percentage'=>$values['maximum']?round($values['earned']/$values['maximum']*100,2):null,'applicable'=>$values['applicable']];arsort($hazards);return['answeredItems'=>$answered,'expectedItems'=>$expected,'emergencyCount'=>$emergencies,'technicalAssistanceCount'=>$ta,'technicalAssistanceOpen'=>$taOpen,'technicalAssistanceOngoing'=>$taOngoing,'continuity'=>$continuity,'hazards'=>$hazards,'domainPerformance'=>$domainPerformance];}
function analytics_metrics(array $rows):array{$metrics=dashboard_metrics($rows);$responses=['Compliant'=>0,'Partially Compliant'=>0,'Not Compliant'=>0,'Not Applicable'=>0];$taStatuses=[];$byDistrict=[];foreach($rows as $r){$district=trim((string)$r['district'])?:'Unassigned District';$byDistrict[$district]=($byDistrict[$district]??0)+1;$data=json_decode((string)$r['data'],true);if(!is_array($data))continue;foreach((is_array($data['checklist']??null)?$data['checklist']:[]) as $item){$status=(string)($item['status']??'');if(isset($responses[$status]))$responses[$status]++;}$taRows=is_array($data['technicalAssistanceRecords']??null)?$data['technicalAssistanceRecords']:[];if(!$taRows&&!empty($data['overallStatus']))$taRows=[['taStatus'=>$data['overallStatus']]];foreach($taRows as $item){$status=trim((string)($item['taStatus']??''))?:'Not specified';$taStatuses[$status]=($taStatuses[$status]??0)+1;}}arsort($taStatuses);arsort($byDistrict);$metrics['responses']=$responses;$metrics['responseTotal']=array_sum($responses);$metrics['technicalAssistanceStatuses']=$taStatuses;$metrics['technicalAssistanceCompleted']=$taStatuses['Completed']??0;$metrics['byDistrict']=array_map(fn($district,$count)=>['district'=>$district,'count'=>$count],array_keys($byDistrict),array_values($byDistrict));return $metrics;}
$route=trim((string)($_GET['route']??''),'/');$method=$_SERVER['REQUEST_METHOD'];$db=db();
try{
if($route==='register'&&$method==='POST'){$b=body();$un=clean_user($b['username']??'');$email=strtolower(trim((string)($b['email']??'')));$district=canonical_district($b['district']??'');if(empty($b['district'])||empty($b['schoolName'])||empty($b['schoolId'])||!$un||!$email||empty($b['password']))out(['error'=>'All registration fields are required.'],400);if(!filter_var($email,FILTER_VALIDATE_EMAIL))out(['error'=>'Enter a valid email address.'],400);if(!$district)out(['error'=>'The district name is not recognized. Select the correct district from the list.'],400);if(($b['password']??'')!==($b['confirmPassword']??''))out(['error'=>'Passwords do not match.'],400);if(strlen((string)$b['password'])<8)out(['error'=>'Password must be at least 8 characters.'],400);$s=$db->prepare('SELECT 1 FROM users WHERE username=? OR email=?');$s->execute([$un,$email]);if($s->fetchColumn())out(['error'=>'An account already uses this username or email address.'],409);$values=[uuid(),$un,$email,password_hash((string)$b['password'],PASSWORD_DEFAULT),trim((string)$b['schoolName']),'user','inactive',$district,trim((string)$b['schoolName']),trim((string)$b['schoolId']),now()];try{write_retry(function()use($db,$values){$s=$db->prepare('INSERT INTO users(id,username,email,password_hash,name,role,status,district,school_name,school_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)');return $s->execute($values);});}catch(PDOException $e){if(str_contains(strtolower($e->getMessage()),'unique'))out(['error'=>'An account already uses this username or email address.'],409);throw $e;}out(['ok'=>true,'district'=>$district]);}
if($route==='login'&&$method==='POST'){$b=body();$s=$db->prepare('SELECT * FROM users WHERE username=?');$s->execute([clean_user($b['username']??'')]);$u=$s->fetch();if(!$u||$u['status']!=='active'||!password_verify((string)($b['password']??''),$u['password_hash']))out(['error'=>'Invalid username or password.'],401);$u=normalize_user_district($db,$u);touch_presence($db,$u['id']);out(['token'=>sign_token(['id'=>$u['id'],'role'=>$u['role'],'exp'=>time()+28800]),'user'=>user_row($u)]);}
if($route==='me'&&$method==='GET')out(['user'=>user_row(current_user())]);
if($route==='profile-photo'&&$method==='POST'){$u=current_user();$b=body();$photo=trim((string)($b['photo']??''));if($photo!==''){if(!preg_match('#^data:image/(?:jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$#',$photo,$m))out(['error'=>'Choose a valid JPG, PNG, or WebP image.'],400);$binary=base64_decode($m[1],true);if($binary===false||strlen($binary)>600000)out(['error'=>'The profile photo is too large. Choose a smaller image.'],413);}write_retry(function()use($db,$photo,$u){$s=$db->prepare('UPDATE users SET profile_photo=? WHERE id=?');return $s->execute([$photo,$u['id']]);});out(['ok'=>true,'profilePhoto'=>$photo]);}
if($route==='presence'&&$method==='POST'){$u=current_user();touch_presence($db,$u['id']);out(['ok'=>true]);}
if($route==='logout'&&$method==='POST'){$u=current_user();$s=$db->prepare('DELETE FROM presence WHERE user_id=?');$s->execute([$u['id']]);out(['ok'=>true]);}
if($route==='users'&&$method==='GET'){current_user(true);$users=array_map(fn($u)=>normalize_user_district($db,$u),$db->query('SELECT * FROM users ORDER BY created_at DESC')->fetchAll());$s=$db->prepare('SELECT p.user_id FROM presence p JOIN users u ON u.id=p.user_id WHERE p.last_seen>=? AND u.status="active"');$s->execute([online_cutoff()]);$online=array_fill_keys($s->fetchAll(PDO::FETCH_COLUMN),true);$rows=array_map(function($u)use($online){$row=user_row($u,false);$row['online']=isset($online[$u['id']]);return $row;},$users);out(['users'=>$rows,'onlineUsers'=>count($online)]);}
if($route==='users/update'&&$method==='POST'){current_user(true);$b=body();if(!in_array($b['status']??'',['active','inactive'],true))out(['error'=>'Invalid account status.'],400);write_retry(function()use($db,$b){$s=$db->prepare('UPDATE users SET status=? WHERE id=? AND role<>"admin"');return $s->execute([$b['status'],$b['id']??'']);});out(['ok'=>true]);}
if($route==='users/delete'&&$method==='POST'){current_user(true);$b=body();write_retry(function()use($db,$b){$s=$db->prepare('DELETE FROM users WHERE id=? AND role<>"admin"');return $s->execute([$b['id']??'']);});out(['ok'=>true]);}
if($route==='users/reset-password'&&$method==='POST'){current_user(true);$b=body();$password=temporary_password();$hash=password_hash($password,PASSWORD_DEFAULT);$updated=write_retry(function()use($db,$b,$hash){$s=$db->prepare('UPDATE users SET password_hash=? WHERE id=? AND role<>"admin"');$s->execute([$hash,$b['id']??'']);return $s->rowCount();});if(!$updated)out(['error'=>'School account not found.'],404);out(['ok'=>true,'temporaryPassword'=>$password]);}
if($route==='draft'&&$method==='GET'){$u=current_user();$s=$db->prepare('SELECT data FROM drafts WHERE user_id=?');$s->execute([$u['id']]);$v=$s->fetchColumn();out(['draft'=>$v?json_decode((string)$v,true):null]);}
if($route==='draft'&&$method==='POST'){$u=current_user();$b=body();$data=is_array($b['data']??null)?$b['data']:[];$data['score']=score($data['checklist']??[]);$data['savedAt']=now();$values=[$u['id'],json_encode($data,JSON_UNESCAPED_UNICODE),$data['savedAt']];write_retry(function()use($db,$values){$s=$db->prepare('INSERT INTO drafts(user_id,data,saved_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data,saved_at=excluded.saved_at');return $s->execute($values);});out(['ok'=>true,'score'=>$data['score'],'savedAt'=>$data['savedAt']]);}
if($route==='submit'&&$method==='POST'){$u=current_user();if($u['role']==='admin')out(['error'=>'Administrator cannot submit a school report.'],400);$b=body();$reportId=trim((string)($b['reportId']??''));$saved=$db->prepare('SELECT data FROM drafts WHERE user_id=?');$saved->execute([$u['id']]);$savedData=$saved->fetchColumn();if(!$savedData)out(['error'=>'Save the M&E Tool before submitting.'],409);$data=json_decode((string)$savedData,true);if(!is_array($data))out(['error'=>'The saved M&E Tool could not be read. Save it again before submitting.'],409);$data['score']=score($data['checklist']??[]);if($reportId!==''){$s=$db->prepare('SELECT * FROM reports WHERE id=? AND user_id=?');$s->execute([$reportId,$u['id']]);$existing=$s->fetch();if(!$existing)out(['error'=>'Submission not found.'],404);$deadline=(strtotime((string)$existing['submitted_at'])?:0)+86400;if(time()>$deadline)out(['error'=>'The 24-hour editing period for this submission has expired.'],403);$data['updatedAt']=now();$values=[json_encode($data['score']),json_encode($data,JSON_UNESCAPED_UNICODE),$u['district'],$u['school_name'],$u['school_id'],$reportId,$u['id']];write_retry(function()use($db,$values){$s=$db->prepare('UPDATE reports SET score=?,data=?,district=?,school_name=?,school_id=?,status="Updated" WHERE id=? AND user_id=?');return $s->execute($values);});out(['ok'=>true,'id'=>$reportId,'score'=>$data['score'],'updated'=>true]);}$existing=$db->prepare('SELECT id FROM reports WHERE user_id=? LIMIT 1');$existing->execute([$u['id']]);if($existing->fetchColumn())out(['error'=>'This school has already submitted the M&E Tool. Use Edit Submission within the 24-hour editing period.'],409);$id=uuid();$submitted=now();$values=[$id,$u['id'],$u['username'],$u['district'],$u['school_name'],$u['school_id'],$submitted,'Submitted',json_encode($data['score']),json_encode($data,JSON_UNESCAPED_UNICODE)];write_retry(function()use($db,$values){$s=$db->prepare('INSERT INTO reports(id,user_id,username,district,school_name,school_id,submitted_at,status,score,data) VALUES(?,?,?,?,?,?,?,?,?,?)');return $s->execute($values);});out(['ok'=>true,'id'=>$id,'score'=>$data['score']]);}
if($route==='submissions'&&$method==='GET'){current_user(true);$rows=$db->query('SELECT id,user_id,username,district,school_name,school_id,submitted_at,status,score FROM reports ORDER BY submitted_at DESC LIMIT 5000')->fetchAll();out(['submissions'=>array_map(fn($r)=>report_row($r,false),$rows)]);}
if($route==='submission'&&$method==='GET'){current_user(true);$s=$db->prepare('SELECT * FROM reports WHERE id=?');$s->execute([$_GET['id']??'']);$r=$s->fetch();if(!$r)out(['error'=>'Report not found.'],404);out(['report'=>report_row($r,true)]);}
if($route==='my-submissions'&&$method==='GET'){$u=current_user();$s=$db->prepare('SELECT * FROM reports WHERE user_id=? ORDER BY submitted_at DESC');$s->execute([$u['id']]);out(['submissions'=>array_map(fn($r)=>report_row($r,true),$s->fetchAll())]);}
if($route==='dashboard'&&$method==='GET'){current_user(true);$registered=(int)$db->query('SELECT COUNT(*) FROM users WHERE role="user"')->fetchColumn();$active=(int)$db->query('SELECT COUNT(*) FROM users WHERE role="user" AND status="active"')->fetchColumn();$districts=(int)$db->query('SELECT COUNT(DISTINCT district) FROM users WHERE role="user" AND district<>""')->fetchColumn();$onlineQuery=$db->prepare('SELECT COUNT(*) FROM presence p JOIN users u ON u.id=p.user_id WHERE p.last_seen>=? AND u.status="active"');$onlineQuery->execute([online_cutoff()]);$online=(int)$onlineQuery->fetchColumn();$summaryRows=$db->query('SELECT id,user_id,username,district,school_name,school_id,submitted_at,status,score FROM reports ORDER BY submitted_at DESC LIMIT 5000')->fetchAll();$latestRows=$db->query('SELECT r.* FROM reports r WHERE r.id=(SELECT r2.id FROM reports r2 WHERE r2.user_id=r.user_id ORDER BY r2.submitted_at DESC,r2.id DESC LIMIT 1) ORDER BY r.submitted_at DESC')->fetchAll();out(['registeredSchools'=>$registered,'submissions'=>count($summaryRows),'activeUsers'=>$active,'onlineUsers'=>$online,'districts'=>$districts,'reports'=>array_map(fn($r)=>report_row($r,false),$summaryRows),'latest'=>array_map(fn($r)=>report_row($r,false),$latestRows),'metrics'=>dashboard_metrics($latestRows)]);}
if($route==='change-password'&&$method==='POST'){$u=current_user(true);$b=body();if(!password_verify((string)($b['currentPassword']??''),$u['password_hash']))out(['error'=>'Current password is incorrect.'],400);if(strlen((string)($b['newPassword']??''))<10)out(['error'=>'New password must be at least 10 characters.'],400);$hash=password_hash((string)$b['newPassword'],PASSWORD_DEFAULT);write_retry(function()use($db,$hash,$u){$s=$db->prepare('UPDATE users SET password_hash=? WHERE id=?');return $s->execute([$hash,$u['id']]);});out(['ok'=>true]);}
if($route==='analytics'&&$method==='GET'){current_user(true);$latestRows=$db->query('SELECT r.* FROM reports r WHERE r.id=(SELECT r2.id FROM reports r2 WHERE r2.user_id=r.user_id ORDER BY r2.submitted_at DESC,r2.id DESC LIMIT 1) ORDER BY r.submitted_at DESC')->fetchAll();out(['latest'=>array_map(fn($r)=>report_row($r,false),$latestRows),'analytics'=>analytics_metrics($latestRows)]);}
out(['error'=>'Not found.'],404);
}catch(PDOException $e){error_log($e->getMessage());out(['error'=>'Database operation failed. Please try again.'],500);}catch(Throwable $e){error_log($e->getMessage());out(['error'=>'Server error.'],500);}
